### ISSUE TITLE
Can't set an initial color value

### ISSUE THREAD

**Issue by hayk94** [JeroenvO/html5-colorpicker#2]
I am trying to set an initial value as is provided in the documentation. But it seems to not work. the color is not set.

```
colorPicker1 = new colorPicker(document.getElementById('colorPicker1'), {
	h: 0,
	s: 100,
	v: 100,
	bgcolor: 'rgba(50,50,50,0)',
	onColorChange: function(){
		var color = this.getColorHSV();
		document.getElementById('colorPickerValue').innerHTML = "Color h:"+color.h+" s: "+ color.s+" v: "+ color.v;
		},
	onCenterClick: function(){
		window.alert('You clicked the center!');
		}
});
```

**Comment by JeroenvO** [comment]
I think your scaling is wrong, the limits are:
H: 0-2pi
S: 0-1
V: 0-1

If that doesn't work please let me know. 
Good luck!

**Comment by hayk94** [comment]
I do not have much knowledge about this color stuff, thus I use a rgb to hsv converter which converts with the values as I provided. Do you know any converters that do it with the scale you provided?

**Comment by JeroenvO** [comment]
Make sure the minimum value for all three values is zero, the maximum value for H should be 2pi (=6.28), the maximum value for s and V should be 1.0

Assuming that your three values are between 0 and 100, divide s and V by 100 and for H divide by 100/(6.28)

⁣Sent from BlueMail ​

**Comment by hayk94** [comment]
Well it works this way however I get a whole different color after dividing. I guess dividing by (100/6.28) is not very acute. I also tried doing it with 2*Math.PI but still the color is being different. Need to figure out the conversion part. Thanks for your help.

**Comment by hayk94** [comment]
Here I found a good conversion function https://gist.github.com/mjackson/5311256
```
/**
 * Converts an RGB color value to HSV. Conversion formula
 * adapted from http://en.wikipedia.org/wiki/HSV_color_space.
 * Assumes r, g, and b are contained in the set [0, 255] and
 * returns h, s, and v in the set [0, 1].
 *
 * @param   Number  r       The red color value
 * @param   Number  g       The green color value
 * @param   Number  b       The blue color value
 * @return  Array           The HSV representation
 */
function rgbToHsv(r, g, b) {
  r /= 255, g /= 255, b /= 255;

  var max = Math.max(r, g, b), min = Math.min(r, g, b);
  var h, s, v = max;

  var d = max - min;
  s = max == 0 ? 0 : d / max;

  if (max == min) {
    h = 0; // achromatic
  } else {
    switch (max) {
      case r: h = (g - b) / d + (g < b ? 6 : 0); break;
      case g: h = (b - r) / d + 2; break;
      case b: h = (r - g) / d + 4; break;
    }

    h /= 6;
  }

  return [ h, s, v ];
}
```
